name: UniqueGenerators
version: ${project.version}
depend:
  - SmartInvs
main: me.imbuzz.dev.UniqueGenerators
authors: [ ImBuzz ]

commands:
  generators:
    description: Base command to use generators